max_workers: 15
model:
  name: "internvl"
  models_string: "OpenGVLab/InternVL-Chat-Chinese-V1-2-Plus"
  temperature: 0
  max_tokens: 2000
  batch_size: 8

data:
  images: "dataset/images"
  dataset: "dataset/dataset.jsonl"

prompt:
  type: "complex"
  single: True

results:
  suffix: ""
  results_path: "results"
  responses_path: "model_responses"