max_workers: 15
model:
  name: "idefics80b"
  models_string: "HuggingFaceM4/idefics-80b-instruct"
  temperature: 0
  max_tokens: 2000
  batch_size: 8

data:
  images: "dataset/images"
  dataset: "dataset/dataset.jsonl"

prompt:
  type: "oss"
  single: True

results:
  suffix: ""
  results_path: "results"
  responses_path: "model_responses"